name: skybase

services:
  db:
    image: mysql:latest
    container_name: skybase_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skybase
      MYSQL_USER: skybase
      MYSQL_PASSWORD: skybase
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uskybase -pskybase -e'USE skybase'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 5s
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: skybase_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: skybase_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8082:80"
volumes:
  dbdata: